apiVersion: v1
kind: Pod
metadata:
  name: priyeshpod2
  namespace: default
  labels:
    name: priyeshpod2
    app: priyeshapp2
spec:
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
# apply redis app conatiner  
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432